### ISSUE TITLE
Pause and "stop"?

### ISSUE THREAD

**Issue by tiagosiebler** [tropicbliss/symphonia#1]
Can you pause or even stop (resetting position to start) something that's playing? I've been looking at a way to do something like a sound board (a silly hobby project) in node. 

If the same button is pushed quickly, it should interrupt the previous sound that might still be playing and immediately play the sound from the start again. Most libraries seem to just fire & forget when playing a sound (with no way of stopping it once it started).

**Comment by tropicbliss** [comment]
I’ll look into it 👍

**Comment by tiagosiebler** [comment]
Thank you!

**Comment by tropicbliss** [comment]
Feature added in 843fb6a1c73705959d050a60e4cfc62d77853927.

There is a caveat in which the audio playback library i'm depending on does not allow seeking back to the start after it is played. Once you call stop() the audio will never play again. Play() and pause() will work as per usual. See the readme on how to use those methods.

**Comment by tropicbliss** [comment]
Added in 0.2.9

**Comment by tiagosiebler** [comment]
Cool! Thank you so much, as long as there's a way to interrupt something currently playing and then I can just restart it using playFromBuf I guess if I want to replay it from start. Thank you!
